[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services.app]
build.dockerfilePath = "Dockerfile"
variables.NODE_ENV = "production"
variables.PORT = "5000"
